# Generated by Django 2.2.12 on 2020-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
