# Generated by Django 2.2.12 on 2020-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20200514_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_Active',
            field=models.BooleanField(default=False),
        ),
    ]
