# Generated by Django 2.2.12 on 2020-05-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_child_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
