# Generated by Django 2.2.12 on 2020-05-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(choices=[('Class_1', 'Class 1'), ('Class_2', 'Class 2'), ('Class_3', 'Class 3'), ('Class_4', 'Class 4'), ('Class_5', 'Class 5'), ('Class_6', 'Class 6'), ('Class_7', 'Class 7'), ('Class_8', 'Class 8'), ('Class_9', 'Class 9'), ('Class_10', 'Class 10'), ('Class_11', 'Class 11'), ('Class_12', 'Class 12')], default='Class_12', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=50)),
                ('Staff_Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(max_length=50)),
                ('Material', models.FileField(upload_to='Documents/')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.Subject')),
            ],
        ),
    ]
