# Generated by Django 2.2.12 on 2020-05-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20200524_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Class_Name',
            field=models.CharField(choices=[('Class_1', 'Class 1'), ('Class_2', 'Class 2'), ('Class_3', 'Class 3'), ('Class_4', 'Class 4'), ('Class_5', 'Class 5'), ('Class_6', 'Class 6'), ('Class_7', 'Class 7'), ('Class_8', 'Class 8'), ('Class_9', 'Class 9'), ('Class_10', 'Class 10'), ('Class_11', 'Class 11'), ('Class_12', 'Class 12')], default='Class_12', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='Material_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
