# Generated by Django 2.2.12 on 2020-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20200524_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Subject_Image',
            field=models.ImageField(default=1, upload_to='ClassImages/'),
            preserve_default=False,
        ),
    ]
