# Generated by Django 2.2.12 on 2020-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_subject_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Upload_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
